# Generated by Django 5.2.6 on 2025-11-16 11:12

import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivocomentario',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Archivo de Comentario', 'verbose_name_plural': 'Archivos de Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='archivoticket',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Archivo de Ticket', 'verbose_name_plural': 'Archivos de Tickets'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['fecha'], 'verbose_name': 'Historial de Estado', 'verbose_name_plural': 'Historiales de Estado'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='archivocomentario',
            name='archivo',
            field=models.FileField(upload_to='comentarios/archivos/%Y/%m/%d/', validators=[tickets.models.validar_tamano_archivo, tickets.models.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='archivoticket',
            name='archivo',
            field=models.FileField(upload_to='tickets/archivos/%Y/%m/%d/', validators=[tickets.models.validar_tamano_archivo, tickets.models.validar_extension_archivo]),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='tickets_tic_estado_2f7a31_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['asignado_a', 'estado'], name='tickets_tic_asignad_da5d81_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['creador'], name='tickets_tic_creador_7e509b_idx'),
        ),
    ]
