# Generated by Django 5.2.6 on 2025-11-25 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_archivocomentario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#3498db', help_text='Color hexadecimal para el badge', max_length=7)),
                ('puede_ver_metricas', models.BooleanField(default=False, verbose_name='Puede ver métricas')),
                ('puede_ver_todos_tickets', models.BooleanField(default=False, verbose_name='Puede ver todos los tickets')),
                ('puede_asignar_tickets', models.BooleanField(default=False, verbose_name='Puede asignar tickets')),
                ('puede_cambiar_estado', models.BooleanField(default=False, verbose_name='Puede cambiar estado de tickets')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Puede gestionar usuarios')),
                ('puede_crear_roles', models.BooleanField(default=False, verbose_name='Puede crear roles personalizados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol Personalizado',
                'verbose_name_plural': 'Roles Personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('fecha_ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_creados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol_personalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='tickets.rolpersonalizado')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='InvitacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('grupo_django', models.CharField(choices=[('Administrador', 'Administrador'), ('Técnico', 'Técnico'), ('Usuario', 'Usuario')], default='Usuario', max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(editable=False, max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje_personalizado', models.TextField(blank=True)),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('rol_personalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.rolpersonalizado')),
            ],
            options={
                'verbose_name': 'Invitación de Usuario',
                'verbose_name_plural': 'Invitaciones de Usuarios',
                'ordering': ['-fecha_invitacion'],
            },
        ),
    ]
