# Generated by Django 5.2.6 on 2025-09-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_historialestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(max_length=50),
        ),
    ]
