# Generated by Django 5.2.6 on 2025-11-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rolpersonalizado_perfilusuario_invitacionusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_ultima_actividad',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invitacionusuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='invitacionusuario',
            name='grupo_django',
            field=models.CharField(default='Usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='invitacionusuario',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='puede_asignar_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='puede_cambiar_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='puede_crear_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='puede_gestionar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='puede_ver_metricas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolpersonalizado',
            name='puede_ver_todos_tickets',
            field=models.BooleanField(default=False),
        ),
    ]
