# Generated by Django 5.2.6 on 2025-11-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_categoria_remove_ticket_area_afectada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitacionUsuario',
        ),
    ]
