# Generated by Django 5.2.6 on 2025-11-25 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_delete_invitacionusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='notificaciones_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificaciones_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_whatsapp',
            field=models.CharField(blank=True, help_text='Formato: +57301234567', max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ticket_creado', 'Ticket Creado'), ('ticket_asignado', 'Ticket Asignado'), ('ticket_comentario', 'Nuevo Comentario'), ('estado_cambio', 'Cambio de Estado'), ('ticket_resuelto', 'Ticket Resuelto'), ('ticket_cerrado', 'Ticket Cerrado')], max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('email_enviado', models.BooleanField(default=False)),
                ('email_fecha', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_enviado', models.BooleanField(default=False)),
                ('whatsapp_fecha', models.DateTimeField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.CharField(blank=True, max_length=500)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='tickets_not_usuario_5f9880_idx'), models.Index(fields=['usuario', 'leida'], name='tickets_not_usuario_288401_idx')],
            },
        ),
    ]
