# Generated by Django 5.2.6 on 2025-12-03 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_perfilusuario_notificaciones_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='❓', help_text='Emoji para la categoría', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_faq_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de FAQ',
                'verbose_name_plural': 'Categorías de FAQs',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField(help_text='Puedes usar HTML básico para formato (ul, li, strong, etc.)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden dentro de la categoría')),
                ('activa', models.BooleanField(default=True)),
                ('vistas', models.PositiveIntegerField(default=0, help_text='Cantidad de veces que se ha visto esta pregunta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='tickets.categoriafaq')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_faq_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta FAQ',
                'verbose_name_plural': 'Preguntas FAQs',
                'ordering': ['categoria', 'orden', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=200)),
                ('encontro_resultados', models.BooleanField(default=False)),
                ('cantidad_resultados', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas_faq', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda de FAQ',
                'verbose_name_plural': 'Búsquedas de FAQs',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='tickets_bus_fecha_98e646_idx'), models.Index(fields=['termino'], name='tickets_bus_termino_f8b683_idx')],
            },
        ),
    ]
