# Generated by Django 5.2.6 on 2025-12-03 06:58

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_categoriafaq_preguntafaq_busquedafaq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=tickets.models.imagen_faq_path, verbose_name='Imagen')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_faq', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen FAQ',
                'verbose_name_plural': 'Imágenes FAQs',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
