# Generated by Django 5.2.6 on 2025-12-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_imagenfaq_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntafaq',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen ilustrativa opcional', null=True, upload_to='faqs/imagenes/'),
        ),
    ]
