# Generated by Django 5.2.6 on 2025-12-08 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_agregar_imagen_preguntafaq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolpersonalizado',
            name='puede_validar_prioridad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad_auto_detectada',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ticket_creado', 'Ticket Creado'), ('ticket_asignado', 'Ticket Asignado'), ('ticket_comentario', 'Nuevo Comentario'), ('estado_cambio', 'Cambio de Estado'), ('ticket_resuelto', 'Ticket Resuelto'), ('ticket_cerrado', 'Ticket Cerrado'), ('ticket_requiere_validacion', 'Ticket Requiere Validación')], max_length=50),
        ),
    ]
